<?php
session_start();
require 'vendor/autoload.php';

// Include Google Cloud dependencies using Composer
use Google\Cloud\RecaptchaEnterprise\V1\RecaptchaEnterpriseServiceClient;
use Google\Cloud\RecaptchaEnterprise\V1\Event;
use Google\Cloud\RecaptchaEnterprise\V1\Assessment;
use Google\Cloud\RecaptchaEnterprise\V1\TokenProperties\InvalidReason;

/**
  * Create an assessment to analyze the risk of a UI action.
  * @param string $recaptchaKey The reCAPTCHA key associated with the website/application
  * @param string $token The token generated by the client.
  * @param string $project Your Google Cloud project ID.
  * @param string $action Action name corresponding to the token.
  */
function create_assessment(
  string $recaptchaKey,
  string $token,
  string $project,
  string $action
): bool {
  $client = new RecaptchaEnterpriseServiceClient();
  $projectName = $client->projectName($project);

  $event = (new Event())
    ->setSiteKey($recaptchaKey)
    ->setToken($token);

  $assessment = (new Assessment())
    ->setEvent($event);

  try {
    $response = $client->createAssessment(
      $projectName,
      $assessment
    );

    if ($response->getTokenProperties()->getValid() == false) {
      printf('The CreateAssessment() call failed because the token was invalid for the following reason: ');
      printf(InvalidReason::name($response->getTokenProperties()->getInvalidReason()));
      return false;
    }

    if ($response->getTokenProperties()->getAction() == $action) {
      printf('The score for the protection action is:');
      printf($response->getRiskAnalysis()->getScore());
      return true;
    } else {
      printf('The action attribute in your reCAPTCHA tag does not match the action you are expecting to score');
      return false;
    }
  } catch (exception $e) {
    printf('CreateAssessment() call failed with the following error: ');
    printf($e);
    return false;
  }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $recaptchaKey = '6Lfo1mEqAAAAAAF6GTU9zC77r99uvMHD_7LmxNdB';
  $token = $_POST['g-recaptcha-response'];
  $project = 'lintodo-1728975271071';
  $action = 'LOGIN';

  if (create_assessment($recaptchaKey, $token, $project, $action)) {
    // Process the form data
    $username = $_POST['username'];
    $password = $_POST['password'];
    // Save the user data to the database or perform other actions
    $_SESSION["username"] = $username;
    echo "<script type='text/javascript'>location.href = './main.php';</script>";
    exit();
  } else {
    echo 'CAPTCHA verification failed. Please try again.';
  }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://www.google.com/recaptcha/enterprise.js?render='6Lfo1mEqAAAAAAF6GTU9zC77r99uvMHD_7LmxNdB'"></script>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h3 class="text-center">Sign Up</h3>
                    </div>
                    <div class="card-body bg-light">
                        <form id="signupForm" action="" method="POST" onsubmit="onClick(event)">
                            <div class="form-group">
                                <label for="username">Username:</label>
                                <input type="text" id="username" name="username" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Password:</label>
                                <input type="password" id="password" name="password" class="form-control" required>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script>
      function onClick(e) {
        e.preventDefault();
        grecaptcha.enterprise.ready(async () => {
          const token = await grecaptcha.enterprise.execute('6Lfo1mEqAAAAAAF6GTU9zC77r99uvMHD_7LmxNdB', {action: 'LOGIN'});
          document.getElementById('signupForm').submit();
        });
      }
    </script>
</body>
</html>