name: Push to SFTP

on: workflow_dispatch

jobs:
  push-to-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create variable files
        run: |
            touch vars/db.php
            echo "<?php \$dbn=\"${{ secrets.db }}\";" >> vars/db.php
            touch vars/dbuser.php
            echo "<?php \$dbuser=\"${{ secrets.dbuser }}\";" >> vars/dbuser.php
            touch vars/dbpass.php
            echo "<?php \$dbpass=\"${{ secrets.dbpass }}\";" >> vars/dbpass.php
            touch vars/suggest_path.php
            echo "<?php \$path=\"${{ secrets.suggest_path }}\";" >> vars/suggest_path.php
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: ${{  secrets.username  }}
          # SSH passsword，If a password is set, the secret key pair is ignored
          password: ${{ secrets.password }}
          # your sftp server
          server: ${{ secrets.dserver }}
          # files will copy to under remote_path
          remote_path: ${{ secrets.path }}
