name: Push to SFTP

on:
  push:
    branches:
      - main

jobs:
  push-to-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          # username
          username: eulbert
          # SSH passsword，If a password is set, the secret key pair is ignored
          password: ${{ secrets.password }}
          # your sftp server
          server: hmbldtw.spdns.org
          # files will copy to under remote_path
          remote_path: /home/eulbert/public_html/web/gtodo/lin-todo
