name: Push to SFTP

on:
  push:
    branches:
      - main

jobs:
  push-to-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to SFTP
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
          host: hmbldtw.spdns.org
          port: 22
          username: eulbert
          password: ${{ secrets.password }}
          sourceDir: lin-todo/
          targetDir: /~eulbert/web/gtodo/lin-todo/
